#!/usr/bin/env node
/**
 * Self-hosts the display face.
 *
 * Run once, on a machine with a normal internet connection:
 *     npm run fonts
 *
 * It downloads the exact woff2 files Google Fonts would serve, drops them in
 * src/assets/fonts/, and writes src/assets/css/fonts.css with the @font-face
 * rules. The build detects that file and switches over automatically:
 *
 *   - the fonts get <link rel="preload">ed instead of discovered late
 *   - no request to fonts.googleapis.com or fonts.gstatic.com at all
 *   - those two origins drop out of the Content Security Policy
 *
 * Re-run it to update. Delete src/assets/css/fonts.css to go back to the CDN.
 */
const fs = require("fs");
const path = require("path");
const https = require("https");

const FAMILY = "Instrument+Serif:ital@0;1";
const CSS_URL = `https://fonts.googleapis.com/css2?family=${FAMILY}&display=swap`;
// A modern desktop UA is what makes Google serve woff2 rather than legacy formats.
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

const FONT_DIR = path.join(__dirname, "..", "src", "assets", "fonts");
const CSS_OUT = path.join(__dirname, "..", "src", "assets", "css", "fonts.css");

function get(url, binary = false) {
  return new Promise((resolve, reject) => {
    https
      .get(url, { headers: { "User-Agent": UA } }, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          return resolve(get(res.headers.location, binary));
        }
        if (res.statusCode !== 200) return reject(new Error(`${res.statusCode} for ${url}`));
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(binary ? Buffer.concat(chunks) : Buffer.concat(chunks).toString("utf8")));
      })
      .on("error", reject);
  });
}

(async () => {
  console.log("Fetching font CSS from Google…");
  const css = await get(CSS_URL);

  // Each @font-face block gives us a style (normal/italic) and a woff2 URL.
  const blocks = css.split("@font-face").slice(1);
  const wanted = [];
  for (const b of blocks) {
    const url = (b.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    const style = /font-style:\s*italic/.test(b) ? "italic" : "normal";
    const weight = (b.match(/font-weight:\s*(\d+)/) || [, "400"])[1];
    // Google serves one block per unicode-range; the latin one is enough here.
    const isLatin = /unicode-range:[^;]*U\+0000/i.test(b) || !/unicode-range/i.test(b);
    if (url && isLatin) wanted.push({ url, style, weight });
  }
  if (!wanted.length) throw new Error("No woff2 URLs found in the Google Fonts CSS.");

  fs.mkdirSync(FONT_DIR, { recursive: true });
  const faces = [];
  for (const f of wanted) {
    const name = `instrument-serif-${f.weight}${f.style === "italic" ? "-italic" : ""}.woff2`;
    process.stdout.write(`  ${name} … `);
    fs.writeFileSync(path.join(FONT_DIR, name), await get(f.url, true));
    console.log("ok");
    faces.push(
      `@font-face{font-family:"Instrument Serif";font-style:${f.style};font-weight:${f.weight};font-display:swap;src:url("/assets/fonts/${name}") format("woff2")}`
    );
  }

  fs.writeFileSync(
    CSS_OUT,
    "/* Generated by `npm run fonts`. Do not edit — re-run the script instead. */\n" +
      faces.join("\n") +
      "\n"
  );

  console.log(`\nWrote ${wanted.length} font file(s) and src/assets/css/fonts.css.`);
  console.log("The next build will preload them and drop Google Fonts from the CSP.");
})().catch((e) => {
  console.error("\nCouldn't self-host the fonts:", e.message);
  console.error("No harm done — the site keeps using Google Fonts. Try again with a connection.");
  process.exit(1);
});
